#!/usr/bin/python3
from argparse import ArgumentParser
from swarmais.models import train_ffnn


if __name__ == "__main__":
    parser = ArgumentParser(
        description="Trains and Evaluates FFNN on Parsed AIS Dataset"
    )
    parser.add_argument('-parsed_data',
                        action="store",
                        type=str,
                        dest="parsed_dataset_fp",
                        required=True)
    parser.add_argument('-graphlogdir',
                        action="store",
                        type=str,
                        dest="graphlogdir",
                        default="graphlogs")
    parser.add_argument('-savedmodelsdir',
                        action="store",
                        type=str,
                        dest='models',
                        default="models")
    parser.add_argument('-save_path',
                        action="store",
                        type=str,
                        dest="savepath",
                        default="data.csv")
    parser.add_argument('-layers',
                        action="store",
                        type=int,
                        nargs='+',
                        default=128)
    parser.add_argument('-optimizer',
                        action='store',
                        type=str,
                        default='Adam')
    parser.add_argument('-total_iters_per_period',
                        action="store",
                        type=int,
                        default=50)
    parser.add_argument('-batch_size',
                        action="store",
                        type=int,
                        default=64)
    parser.add_argument('-num_epochs',
                        action='store',
                        type=int,
                        default=1000)
    parser.add_argument('-seed',
                        action='store',
                        type=int,
                        default=0)

    results = parser.parse_args()
    train_ffnn(results.parsed_dataset_fp,
               results.graphlogdir,
               results.models,
               results.layers,
               results.optimizer,
               results.total_iters_per_period,
               results.batch_size,
               results.num_epochs,
               results.seed)